[theme]
primaryColor = "#01696f"
backgroundColor = "#f7f6f2"
secondaryBackgroundColor = "#ffffff"
textColor = "#28251d"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
